version: '3'
services:
  # PHP Service
  lacorp-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: lacorp-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: lacorp-app
      SERVICE_TAGS: dev
    working_dir: /var/www
    networks:
      - lacorp-network

  # Nginx Service
  lacorp-nginx:
    image: nginx:alpine
    container_name: lacorp-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - lacorp-network

  # MySQL Service
  lacorp-mysql:
    image: mysql:5.7.22
    container_name: lacorp-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: lacorp
      MYSQL_ROOT_PASSWORD: lacorp
      SERVICE_TAGS: dev
      SERVICE_NAME: lacorp-mysql
    networks:
      - lacorp-network

# Docker Networks
networks:
  lacorp-network:
    driver: bridge
